spring:
  application:
    name: @project.name@
    version: @project.version@
  main:
    banner-mode: "LOG"

  datasource:
    url: jdbc:mariadb://localhost:3306/movies_db
    username: user
    password: secret
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    enabled: true
    change-log: classpath:/db.changelog-master.yaml

  security:
    users:
      - username: user1
        password: pass1
        roles:
          - USER
      - username: user2
        password: pass2
        roles:
          - USER
      - username: user3
        password: pass3
        roles:
          - USER

rate-limiter:
  max-requests: 5
  time-window: 60000 # 1 minute

management:
  endpoint:
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  prometheus:
    metrics:
      export:
        enabled: true

spring-doc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    use-root-path: true

imdb-files:
  base-path: /imdb
